on:
  push:
    branches: '*'

name: Build-Docker

jobs:
  build:
    if: "contains(github.event.head_commit.message, '[docker]')"
    runs-on: ubuntu-latest
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    strategy:
      matrix:
        config:
          - {os: fedora-33, r: '3.6.3'}

    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Build and push Docker images
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: xiangyunhuang/masr
          tags: latest
