on:
  push:
    branches: '*'

name: Build-Docker

jobs:
  build:
    if: "contains(github.event.head_commit.message, '[docker]')"
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    strategy:
      matrix:
        config:
          - {os: ubuntu-18.04, r: '4.0.0'}

    steps:
      - name: Build  Docker Image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: xiangyunhuang/masr
          tags: latest
